# 🏃‍♂️ Project: FitTrack Performance Analysis (Weeks 1 & 2)

**Role:** Junior Data Analyst at *FitTrack Inc.*
**Objective:** The product team needs a set of Python scripts to process raw heart rate data coming from a new wearable device. Your goal is to build the basic logic using Python and then optimize it using NumPy for larger datasets.

---

## 🟢 Part 1: Basic Python Logic (Week 1)
**Goal:** Review variables, control flow, and functions.

### 📝 Task 1.1: The Heart Rate Zone Checker
We need a function to categorize an athlete's effort level in real-time.

1.  **Variables:** Create variables for an athlete named `"Alex"`, a resting heart rate of `60`, and a current heart rate of `145`.
2.  **Function:** Write a function `check_zone(current_hr)` that returns:
    * "Resting" if heart rate is $< 80$
    * "Aerobic Zone" if heart rate is between $80$ and $150$
    * "Anaerobic Zone" if heart rate is $> 150$
3.  **Output:** Call the function and print the result for Alex.

> **⬇️ Your Solution Below:**

In [1]:
athlete_name = "Alex"
resting_hr = 60
current_hr = 145 
def check_zone(current_hr):
    if current_hr < 80:
        return "Resting"
    elif current_hr >= 80 and current_hr <= 150:
        return "Aerobic Zone"
    else:
        return "Anaerobic Zone"
print(f"{athlete_name}'s current zone is:",check_zone(current_hr=current_hr))

Alex's current zone is: Aerobic Zone


## 🔵 Part 2: Data Structures (Week 2 - Ch. 3)
**Goal:** Work with Lists, Dictionaries, and Sets.

### 📝 Task 2.1: Organizing Inventory & Stats
The backend team sent us some unstructured data. We need to organize it.

1.  **Lists:** Create a list called `workouts` containing: `"Running"`, `"Cycling"`, `"Swimming"`, `"Yoga"`, `"HIIT"`. Add `"Boxing"` to the end of the list.
2.  **Dictionaries:** Create a dict called `athlete_pbs` mapping names to their 5k run times: `{'Alex': 25.5, 'Sarah': 22.0, 'Mike': 28.1}`. Access and print Sarah's time.
3.  **Sets:** You have two lists of muscles used in two different workouts.
    * `squat_muscles = {'Quads', 'Glutes', 'Hamstrings'}`
    * `deadlift_muscles = {'Hamstrings', 'Glutes', 'Back'}`
    * Find the **intersection** (muscles used in both).

> **⬇️ Your Solution Below:**

In [2]:
workouts = ["Running", "Cycling", "Swimming", "Yoga", "HIIT"]
workouts.append("Boxing")
print("Workouts:", workouts)

athlete_pbs = {'Alex': 25.5, 'Sarah': 22.0, 'Mike': 28.1}
print("Sarah's 5k time:", athlete_pbs['Sarah'])

Workouts: ['Running', 'Cycling', 'Swimming', 'Yoga', 'HIIT', 'Boxing']
Sarah's 5k time: 22.0


In [3]:
squat_muscles = {'Quads', 'Glutes', 'Hamstrings'}
deadlift_muscles = {'Hamstrings', 'Glutes', 'Back'}
intersection = squat_muscles.intersection(deadlift_muscles)
print("Muscles used in both workouts:", intersection)

Muscles used in both workouts: {'Glutes', 'Hamstrings'}


## 🚀 Part 3: NumPy High-Performance Computing (Week 2 - Ch. 4)
**Goal:** Create ndarrays, perform indexing, and use boolean filtering.

### 📝 Task 3.1: The Heart Rate Matrix
We have recorded the heart rates of **5 athletes** over a **10-minute** intense session.
We need to treat this as a Matrix ($5 \times 10$).

1.  **Import:** Import `numpy` as `np`.
2.  **Create:** Generate a $5 \times 10$ array using `np.random.randint` with values between **100** and **190** (simulating heart rates).
3.  **Analyze:**
    * Calculate the **average** heart rate for *each* athlete (Row-wise / Axis 1).
    * Find the **maximum** heart rate recorded in the entire session.
4.  **Filter:** Use Boolean Indexing to create a new array containing only the heart rates that represent "Peak Performance" (values $> 175$).



> **⬇️ Your Solution Below:**

In [4]:
import numpy as np 
heart_rates = np.random.randint(100,190,(5,10))
print("Heart rates matrix:\n", heart_rates)

Heart rates matrix:
 [[186 157 180 188 141 183 146 141 120 157]
 [181 126 174 143 185 128 187 178 139 149]
 [127 174 124 172 115 181 135 171 151 144]
 [142 166 189 113 183 101 144 116 151 166]
 [186 171 143 185 155 164 160 157 126 182]]


In [5]:
avg_heart_rates = heart_rates.mean(axis=1)
print("Average heart rate for each athlete:", avg_heart_rates)

Average heart rate for each athlete: [159.9 159.  149.4 147.1 162.9]


In [6]:
max_heart_rate = heart_rates.max()
print("Maximum heart rate in session:", max_heart_rate)

Maximum heart rate in session: 189


In [7]:
peak_rates = heart_rates[heart_rates>175]
print("Peak performance heart rates (>175):", peak_rates)

Peak performance heart rates (>175): [186 180 188 183 181 185 187 178 181 189 183 186 185 182]


## ⏱️ Part 4: Vectorization vs. Loops
**Goal:** Prove why we use NumPy for data analysis instead of standard Python lists.

### 📝 Task 4.1: The Speed Test
We have 1 million data points representing sensor readings. We need to square every number.

1.  **Data:** Create a NumPy array `large_array` with $1,000,000$ random numbers.
2.  **Loop Approach:** Write a standard Python `for` loop to square each number and append it to a new list. Time it using the `%%time` magic command.
3.  **Vectorized Approach:** Square the `large_array` directly using NumPy (`large_array ** 2`). Time it using `%%time`.
4.  **Compare:** Observe the difference in execution time.

> **⬇️ Your Solution Below:**

In [8]:
large_arrayl = np.random.random(1000000)
new_arrayl = np.array([])

In [9]:
%%time
squared_list = []
for i in large_arrayl:
    squared_list.append(i ** 2)

CPU times: user 145 ms, sys: 7.41 ms, total: 152 ms
Wall time: 165 ms


In [10]:
%%time
new_arrayl = large_arrayl ** 2

CPU times: user 1.33 ms, sys: 2.66 ms, total: 3.99 ms
Wall time: 2.36 ms
